---
- name: Win update
  hosts: Windows-server
  gather_facts: false
  tasks:
  - name: Update Windows
    win_updates:
      category_names:
       - SecurityUpdates
       - CriticalUpdates
    register: update_result
    failed_when: 'update_result.failed_update_count is defined and update_result.failed_update_count == update_result.found_update_count'
    when: "(update_result is not defined) or (update_result.found_update_count is defined and update_result.found_update_count > 0)"

  - debug:
      var: update_result

  - name: Reboot
    win_reboot:
      shutdown_timeout_sec: 3600
      reboot_timeout_sec: 3600
    when: '(update_result.failed is defined and update_result.failed == True) or (update_result.reboot_required is defined and update_result.reboot_required) or (update_result.failed_update_count is defined and update_result.failed_update_count > 0)'
