---
- name: Win update (search only)
  hosts: Windows-server
  gather_facts: false

  tasks:
  - name: Update Windows
    win_updates:
      log_path: c:\ansible_wu_log.txt
      category_names:
       - SecurityUpdates
       - CriticalUpdates
      state: searched
    register: update_result
    failed_when: 'update_result.failed_update_count is defined and update_result.failed_update_count == update_result.found_update_count'
    when: "(update_result is not defined) or (update_result.found_update_count is defined and update_result.found_update_count > 0)"

  - debug:
      var: update_result
